/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: kenny_pizza (https://sketchfab.com/kenny_pizza)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-coffee-cup-6e6432980e0944219434b81cbc67eacb
title: Low Poly Coffee Cup
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/coffee.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.39, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials.Coffee}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_0.geometry}
            material={materials.Porcelain}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/coffee.gltf");