/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Renafox (https://sketchfab.com/kryik1023)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/awakened-pc-54475c2615f9445d8029ff91f65fc0c7
title: Awakened PC
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/computer.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[31.02, -382.91, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box001__0.geometry}
              material={materials.RootNode}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/computer.gltf");
