/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: peewee.id (https://sketchfab.com/p2eweeworld)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/flat-design-web-b12df26ec16749d1abb589cceac9d1d1
title: Flat Design WEB
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/web.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.95, 0, 0.59]} scale={[2.95, 0.07, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_0.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials["Material.016"]}
          />
        </group>
        <group position={[-1.94, -0.02, 0.26]} scale={[1.52, 0.07, 0.69]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_0.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group position={[0.77, -0.02, 0.51]} scale={[0.94, 0.07, 0.44]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_0.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials["Material.014"]}
          />
        </group>
        <group position={[0.77, -0.02, -0.6]} scale={[0.94, 0.07, 0.44]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_0.geometry}
            material={materials["Material.012"]}
          />
        </group>
        <group position={[0.3, -0.09, 0.5]} scale={[0.26, 0.03, 0.26]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004_0.geometry}
            material={materials["Material.025"]}
          />
        </group>
        <group
          position={[-3.63, -0.07, 1.87]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.11, 0.11, 0.06]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_0.geometry}
            material={materials["Material.019"]}
          />
        </group>
        <group
          position={[-3.31, -0.07, 1.87]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.11, 0.11, 0.06]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_0.geometry}
            material={materials["Material.017"]}
          />
        </group>
        <group
          position={[-3.01, -0.07, 1.87]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.11, 0.11, 0.06]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_0.geometry}
            material={materials["Material.018"]}
          />
        </group>
        <group position={[-0.47, -0.06, 1.85]} scale={[2.28, 0.05, 0.1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_0.geometry}
            material={materials["Material.026"]}
          />
        </group>
        <group position={[0.33, 1.15, -0.3]} scale={[2.96, 0.12, 1.85]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_0.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <group
          position={[0.36, 1.15, -2.01]}
          rotation={[0.04, 0, 0]}
          scale={[2.84, 1.58, 0.17]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_1.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_0.geometry}
            material={materials["Material.007"]}
          />
        </group>
        <group position={[3.11, -0.34, -1.02]} scale={[0.83, 0.05, 1.09]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008_0.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <group position={[3.11, -0.34, 0.15]} scale={[0.91, 0.08, 0.08]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_0.geometry}
            material={materials["Material.009"]}
          />
        </group>
        <group position={[3.12, -0.39, -0.32]} scale={[0.59, 0.02, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_0.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[3.27, 1.15, 2.81]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.56, 0.56, 0.12]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_0.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group position={[-3.28, 1.02, 2.3]} scale={[0.03, 0.04, 0.76]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014_0.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[1.79, 1.15, 3.04]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.41, 0.41, 0.09]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_1.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_0.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <group
          position={[0.8, -0.03, 1.32]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.6, 0.05, 0.07]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_0.geometry}
            material={materials["Material.027"]}
          />
        </group>
        <group
          position={[-2.33, -0.03, -0.66]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-1.14, 0.05, 0.06]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_0.geometry}
            material={materials["Material.020"]}
          />
        </group>
        <group position={[-2.58, 1.15, 3.07]} scale={0.36}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mball008_0.geometry}
            material={materials["Material.024"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/web.gltf");